#### This file will demonstrate, and visualise the key functionalities of the Jax order book implementation. Further, it will measure the walltime speeds for these basic operations.

In [1]:
%load_ext autoreload
%autoreload 2
from functools import partial, partialmethod
from typing import OrderedDict
from jax import numpy as jnp
import jax

#jax.config.update('jax_platform_name', 'cpu')

import gymnax_exchange.jaxes.jaxob_new.JaxOrderBookArrays as job



import random
import time
import timeit

import sys
sys.path.append('/Users/sasrey/AlphaTrade')
import gymnax_exchange




In [2]:
def create_init_book(booksize=10,tradessize=10,pricerange=[2190000,2200000,2210000],quantrange=[0,500],timeinit=[34200,0]):
    qtofill=booksize//3 #fill one third of the available space
    asks=[]
    bids=[]
    orderid=1000
    traderid=1000
    times=timeinit[0]
    timens=timeinit[1]
    for i in range(qtofill):
        asks.append([random.randint(pricerange[1],pricerange[2]),random.randint(quantrange[0],quantrange[1]),orderid,traderid,times,timens])
        times+=random.randint(0,1)
        timens+=random.randint(0,10000)
        bids.append([random.randint(pricerange[1],pricerange[2]),random.randint(quantrange[0],quantrange[1]),orderid+1,traderid+1,times,timens])
        times+=random.randint(0,1)
        timens+=random.randint(0,10000)
        orderid+=2
        traderid+=2
    bids=jnp.concatenate((jnp.array(bids),jnp.ones((booksize-qtofill,6),dtype=jnp.int32)*-1),axis=0)
    asks=jnp.concatenate((jnp.array(asks),jnp.ones((booksize-qtofill,6),dtype=jnp.int32)*-1),axis=0)
    trades=jnp.ones((tradessize,6),dtype=jnp.int32)*-1
    return asks,bids,trades

def create_message(type='limit',side='bid',price=2200000,quant=10,times=36000,timens=0):
    if type=='limit':
        type_num=1
    elif type =='cancel' or type == 'delete':
        type_num=2
    elif type =='market':
        type_num=4
    else:
        raise ValueError('Type is none of: limit, cancel, delete or market')

    if side=='bid':
        side_num=1
    elif side =='ask':
        side_num=-1
    else:
        raise ValueError('Side is none of: bid or ask')
    
    dict_msg={
    'side':side_num,
    'type':type_num,
    'price':price,
    'quantity':quant,
    'orderid':8888,
    'traderid':8888,
    'time':times,
    'time_ns':timens}
    array_msg=jnp.array([type_num,side_num,quant,price,8888,8888,times,timens])
    return dict_msg,array_msg

def create_message_forvmap(type='limit',side='bid',price=2200000,quant=10,times=36000,timens=0,nvmap=10):
    if type=='limit':
        type_num=1
    elif type =='cancel' or type == 'delete':
        type_num=2
    elif type =='market':
        type_num=4
    else:
        raise ValueError('Type is none of: limit, cancel, delete or market')

    if side=='bid':
        side_num=1
    elif side =='ask':
        side_num=-1
    else:
        raise ValueError('Side is none of: bid or ask')
    
    dict_msg={
    'side':jnp.array([side_num]*nvmap),
    'type':jnp.array([type_num]*nvmap),
    'price':jnp.array([price]*nvmap),
    'quantity':jnp.array([quant]*nvmap),
    'orderid':jnp.array([8888]*nvmap),
    'traderid':jnp.array([8888]*nvmap),
    'time':jnp.array([times]*nvmap),
    'time_ns':jnp.array([timens]*nvmap)}
    array_msg=jnp.array([type_num,side_num,quant,price,8888,8888,times,timens]*nvmap)
    return dict_msg,array_msg

Measuring the time for the most basic operations: Adding and order and removing an order from a given side of the book.

In [3]:
## Add an order
n_runs=1000
random.seed(0)
addout=[]
for i in [10,100,1000]:
    asks,bids,trades=create_init_book(booksize=i)
    mdict,marray=create_message(type='limit',side='bid',price=2191200,quant=77)
    out=job.add_order(bids,mdict)
    addout.append(out)
    print("Add time for orderbook of size",i,":",timeit.timeit('val=job.add_order(bids,mdict); jax.block_until_ready(val)',number=n_runs,globals=globals())/n_runs)
    
print(addout[0])

random.seed(0)
#Now do it when vmapped
nvmap=1000
for i,s in enumerate([10,100,1000]):
    asks,bids,trades=create_init_book(booksize=s)
    vmdict,marray=create_message_forvmap(type='limit',side='bid',price=2191200,quant=77,nvmap=nvmap)

    vbids=jnp.array([bids]*nvmap)

    out=job.add_order(bids,mdict)
    outv=jax.vmap(job.add_order,(0,{'orderid': 0, 'price': 0, 'quantity': 0, 'side': 0, 'time': 0, 'time_ns': 0, 'traderid': 0, 'type': 0}))(vbids,vmdict)
    
    print("VMAP add time for orderbook of size",s," \n various incoming order sizes:",timeit.timeit("val=jax.vmap(job.add_order,(0,{'orderid': 0, 'price': 0, 'quantity': 0, 'side': 0, 'time': 0, 'time_ns': 0, 'traderid': 0, 'type': 0}))(vbids,vmdict); jax.block_until_ready(val)",number=n_runs,globals=globals())/n_runs)







Add time for orderbook of size 10 : 0.00011504708090797067
Add time for orderbook of size 100 : 0.00011782379518263042
Add time for orderbook of size 1000 : 0.00016207307414151727
[[2204242     494    1001    1001   34201     663]
 [2209558     456    1003    1003   34203   13163]
 [2204104     465    1005    1005   34203   22984]
 [2191200      77    8888    8888   36000       0]
 [     -1      -1      -1      -1      -1      -1]
 [     -1      -1      -1      -1      -1      -1]
 [     -1      -1      -1      -1      -1      -1]
 [     -1      -1      -1      -1      -1      -1]
 [     -1      -1      -1      -1      -1      -1]
 [     -1      -1      -1      -1      -1      -1]]
VMAP add time for orderbook of size 10  
 various incoming order sizes: 0.0007808422988746315
VMAP add time for orderbook of size 100  
 various incoming order sizes: 0.0010003842131700367
VMAP add time for orderbook of size 1000  
 various incoming order sizes: 0.002885156926000491


In [4]:
## Cancel an order
n_runs=1000
random.seed(0)
cancelout=[]
for i,s in enumerate([10,100,1000]):
    bids=addout[i]
    mdict,marray=create_message(type='cancel',side='bid',price=2191200,quant=77)
    out=job.cancel_order(bids,mdict)
    cancelout.append(out)
    print("Cancel time for orderbook of size",s,":",timeit.timeit('val=job.cancel_order(bids,mdict); jax.block_until_ready(val)',number=n_runs,globals=globals())/n_runs)
cancelout[0]

Cancel time for orderbook of size 10 : 8.145303488709032e-05
Cancel time for orderbook of size 100 : 9.522487688809634e-05
Cancel time for orderbook of size 1000 : 9.36314610298723e-05


Array([[2204242,     494,    1001,    1001,   34201,     663],
       [2209558,     456,    1003,    1003,   34203,   13163],
       [2204104,     465,    1005,    1005,   34203,   22984],
       [     -1,      -1,      -1,      -1,      -1,      -1],
       [     -1,      -1,      -1,      -1,      -1,      -1],
       [     -1,      -1,      -1,      -1,      -1,      -1],
       [     -1,      -1,      -1,      -1,      -1,      -1],
       [     -1,      -1,      -1,      -1,      -1,      -1],
       [     -1,      -1,      -1,      -1,      -1,      -1],
       [     -1,      -1,      -1,      -1,      -1,      -1]],      dtype=int32)

Matching a single order against an identified order from the other side of the book:

In [91]:
matchout=[]

for i,s in enumerate([10,100,1000]):
    _,_,trades=create_init_book(booksize=s)

    bids=cancelout[i]
    idx=job.get_top_bid_order_idx(bids)
    print("Time to get top bid order for order book of size ",s,":",timeit.timeit('val=job.get_top_bid_order_idx(bids); jax.block_until_ready(val)',number=n_runs,globals=globals())/n_runs)

    matchtuple=(bids,1000,0,idx,trades,9999,36000,1)
    bids,qtm,price,idx,trades,agrid,times,timens=job.match_order(matchtuple)
    
    matchout.append((bids,qtm,trades))
    print("Match time for orderbook of size",s,":",timeit.timeit('val=job.match_order(matchtuple); jax.block_until_ready(val)',number=n_runs,globals=globals())/n_runs)
matchout[0]

Time to get top bid order for order book of size  10 : 3.596899705007672e-05
Match time for orderbook of size 10 : 0.00014379851496778428
Time to get top bid order for order book of size  100 : 5.205514398403466e-05
Match time for orderbook of size 100 : 0.00016255285777151584
Time to get top bid order for order book of size  1000 : 5.956477206200361e-05
Match time for orderbook of size 1000 : 0.0001610878980718553


(Array([[2204242,     494,    1001,    1001,   34201,     663],
        [     -1,      -1,      -1,      -1,      -1,      -1],
        [2204104,     465,    1005,    1005,   34203,   22984],
        [     -1,      -1,      -1,      -1,      -1,      -1],
        [     -1,      -1,      -1,      -1,      -1,      -1],
        [     -1,      -1,      -1,      -1,      -1,      -1],
        [     -1,      -1,      -1,      -1,      -1,      -1],
        [     -1,      -1,      -1,      -1,      -1,      -1],
        [     -1,      -1,      -1,      -1,      -1,      -1],
        [     -1,      -1,      -1,      -1,      -1,      -1]],      dtype=int32),
 Array(544, dtype=int32),
 Array([[2209558,     456,    1003,    9999,   36000,       1],
        [     -1,      -1,      -1,      -1,      -1,      -1],
        [     -1,      -1,      -1,      -1,      -1,      -1],
        [     -1,      -1,      -1,      -1,      -1,      -1],
        [     -1,      -1,      -1,      -1,      -1,     

Match against an entire side, continuing until either the full incoming order is matched, the book is empty, or the best price is no longer acceptable to the lim-order.

In [6]:
matchout=[]

for i,s in enumerate([10,100,1000]):
    for j,q in enumerate([0,10,500,1000,10000]):
        _,_,trades=create_init_book(booksize=s,tradessize=s)

        bids=cancelout[i]

        matchtuple=(bids,q,0,trades,9999,36000,1)
        bids,qtm,price,trades=job.match_against_bid_orders(*matchtuple)
        
        matchout.append((bids,qtm,trades))
        print("Match time for orderbook of size",s," \n with an incoming order of size",q,":",timeit.timeit('val=job.match_against_bid_orders(*matchtuple); jax.block_until_ready(val)',number=n_runs,globals=globals())/n_runs)


#Now do it when vmapped (i.e. this skips the cond)
nvmap=1000
for i,s in enumerate([10,100,1000]):
    _,_,trades=create_init_book(booksize=s,tradessize=s)
    bids=cancelout[i]

    vbids=jnp.array([bids]*nvmap)
    vtrades=jnp.array([trades]*nvmap)
    vq=jnp.array([100,100,100,100,100]*(nvmap//5))

    matchtuple=(vbids,vq,0,vtrades,9999,36000,1)
    jax.vmap(job.match_against_bid_orders,((0,0,None,0,None,None,None)))(*matchtuple)
    
    matchout.append((bids,qtm,trades))
    print("VMAP Match time for orderbook of size",s," \n various incoming order sizes:",timeit.timeit('val=jax.vmap(job.match_against_bid_orders,((0,0,None,0,None,None,None)))(*matchtuple); jax.block_until_ready(val)',number=n_runs,globals=globals())/n_runs)




Match time for orderbook of size 10  
 with an incoming order of size 0 : 0.0001248123359400779
Match time for orderbook of size 10  
 with an incoming order of size 10 : 0.00017851380398496984
Match time for orderbook of size 10  
 with an incoming order of size 500 : 0.00022662654402665793
Match time for orderbook of size 10  
 with an incoming order of size 1000 : 0.0002486388268880546
Match time for orderbook of size 10  
 with an incoming order of size 10000 : 0.00022945912810973823
Match time for orderbook of size 100  
 with an incoming order of size 0 : 0.00013440861692652105
Match time for orderbook of size 100  
 with an incoming order of size 10 : 0.0002003891379572451
Match time for orderbook of size 100  
 with an incoming order of size 500 : 0.0002710026849526912
Match time for orderbook of size 100  
 with an incoming order of size 1000 : 0.0003419375908561051
Match time for orderbook of size 100  
 with an incoming order of size 10000 : 0.0024769475860521198
Match time 

Matching is what takes the longest, and increases when the while loop needs to turn for longer. But even for a single iteration, it takes roughly 1.5 times the time than a simple add order.
Next we consider the higher-level message types and include the branching logic required to direct orders across different types and sides of orders.

In [5]:
random.seed(0)
nvmap=1000
outs=[]
for i in [10,100,1000]:
    asks,bids,trades=create_init_book(booksize=i,tradessize=i)
    _,limitmsg=create_message(type='limit',side='bid',price=2191200,quant=77)
    _,cancelmsg=create_message(type='cancel',side='bid',price=2191200,quant=77)
    _,matchmsg=create_message(type='limit',side='ask',price=2191200,quant=100)

    out,_=job.cond_type_side((asks,bids,trades),limitmsg)
    print("Limit order for book of size ",i,":",timeit.timeit('val=job.cond_type_side((asks,bids,trades),limitmsg); jax.block_until_ready(val)',number=n_runs,globals=globals())/n_runs)
    out,_=job.cond_type_side(out,cancelmsg)
    print("Cancel order for book of size ",i,":",timeit.timeit('val=job.cond_type_side(out,cancelmsg); jax.block_until_ready(val)',number=n_runs,globals=globals())/n_runs)
    out,_=job.cond_type_side(out,matchmsg)
    print("Matched limit order for book of size ",i,":",timeit.timeit('val=job.cond_type_side(out,matchmsg); jax.block_until_ready(val)',number=n_runs,globals=globals())/n_runs)
    outs.append(out)

    vasks=jnp.array([asks]*nvmap)
    vbids=jnp.array([bids]*nvmap)
    vtrades=jnp.array([trades]*nvmap)
    vlimitms=jnp.array([limitmsg]*nvmap)
    vcancelms=jnp.array([cancelmsg]*nvmap)
    vmatchms=jnp.array([matchmsg]*nvmap)

    out,_=jax.vmap(job.cond_type_side,((0,0,0),0))((vasks,vbids,vtrades),vlimitms)
    print("VMAP limit order for book of size ",i,":",timeit.timeit('val=jax.vmap(job.cond_type_side,((0,0,0),0))((vasks,vbids,vtrades),vlimitms); jax.block_until_ready(val)',number=n_runs,globals=globals())/n_runs)
    out,_=jax.vmap(job.cond_type_side,((0,0,0),0))(out,vcancelms)
    print("VMAP cancel order for book of size ",i,":",timeit.timeit('val=jax.vmap(job.cond_type_side,((0,0,0),0))(out,vcancelms); jax.block_until_ready(val)',number=n_runs,globals=globals())/n_runs)
    out,_=jax.vmap(job.cond_type_side,((0,0,0),0))(out,vmatchms)
    print("VMAP matched limit order for book of size ",i,":",timeit.timeit('val=jax.vmap(job.cond_type_side,((0,0,0),0))(out,vmatchms); jax.block_until_ready(val)',number=n_runs,globals=globals())/n_runs)


    


Limit order for book of size  10 : 0.00011194318602792918
Cancel order for book of size  10 : 7.982373679988086e-05
Matched limit order for book of size  10 : 0.00016228027804754674
VMAP limit order for book of size  10 : 0.0014024688568897545
VMAP cancel order for book of size  10 : 0.00140687983809039
VMAP matched limit order for book of size  10 : 0.0013927103450987488
Limit order for book of size  100 : 0.00015688729705289008
Cancel order for book of size  100 : 9.710983908735215e-05
Matched limit order for book of size  100 : 0.00020307287015020848
VMAP limit order for book of size  100 : 0.0026488057328388093
VMAP cancel order for book of size  100 : 0.002613553388044238
VMAP matched limit order for book of size  100 : 0.0026109530250541866
Limit order for book of size  1000 : 0.00019547550892457365
Cancel order for book of size  1000 : 9.46054148953408e-05
Matched limit order for book of size  1000 : 0.00024657501303590836
VMAP limit order for book of size  1000 : 0.011749650357