## JAX Order Book Arrays Test Notebook

This notebook demonstrates and visualizes the key functionalities of the JAX order book implementation. 
It tests:
- Basic operations: add_order, cancel_order, match_order
- Higher-level branching: cond_type_side
- Scanning through message arrays

The tests use real LOBSTER sample data (AMZN) from the data directory.

In [13]:
%load_ext autoreload
%autoreload 2

from functools import partial
from jax import numpy as jnp
import jax
import numpy as np
import pandas as pd
import time
import timeit
import os
import sys

# Add the path to the gymnax_exchange module
sys.path.insert(0, '/home/myuser')

# Import the JAX Order Book module and configurations
import gymnax_exchange.jaxob.JaxOrderBookArrays as job
from gymnax_exchange.jaxob.jaxob_config import JAXLOB_Configuration
from gymnax_exchange.jaxob.jorderbook import OrderBook, LobState

# Set up JAX configuration
print(f"JAX version: {jax.__version__}")
print(f"Available devices: {jax.devices()}")

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
JAX version: 0.7.2.dev20260216
Available devices: [CpuDevice(id=0)]


In [14]:
# ============================================================================
# Data Loading Functions - Load real LOBSTER sample data
# ============================================================================

def load_sample_data(data_path: str = "/home/myuser/data/rawLOBSTER/AMZN/Sample"):
    """
    Load LOBSTER sample message and orderbook data.
    
    LOBSTER Format:
    - Message: [time, type, order_id, quantity, price, direction]
        - type: 1=limit, 2=cancel, 3=delete, 4=execute, 5=hidden, 6=cross, 7=halt
        - direction: 1=bid (buy), -1=ask (sell)
    - Orderbook: [ask_price_1, ask_size_1, bid_price_1, bid_size_1, ...]
    
    Returns:
        messages_df: DataFrame with message data
        orderbook_df: DataFrame with orderbook states
    """
    message_file = os.path.join(data_path, "AMZN_2012-06-21_34200000_57600000_message_10.csv")
    orderbook_file = os.path.join(data_path, "AMZN_2012-06-21_34200000_57600000_orderbook_10.csv")
    
    # Load message data
    messages_df = pd.read_csv(message_file, header=None)
    messages_df.columns = ['time', 'type', 'order_id', 'quantity', 'price', 'direction']
    
    # Load orderbook data (10 levels = 40 columns)
    orderbook_df = pd.read_csv(orderbook_file, header=None)
    n_levels = orderbook_df.shape[1] // 4
    columns = []
    for i in range(n_levels):
        columns.extend([f'ask_price_{i+1}', f'ask_size_{i+1}', f'bid_price_{i+1}', f'bid_size_{i+1}'])
    orderbook_df.columns = columns
    
    print(f"Loaded {len(messages_df)} messages and {len(orderbook_df)} orderbook states")
    print(f"Time range: {messages_df['time'].min():.2f} to {messages_df['time'].max():.2f}")
    print(f"Message types: {messages_df['type'].value_counts().to_dict()}")
    
    return messages_df, orderbook_df


def preprocess_messages_to_jax(messages_df: pd.DataFrame, n_msgs: int = None) -> jnp.ndarray:
    """
    Convert LOBSTER messages to JAX format for cond_type_side.
    
    JAX message format: [type, side, quantity, price, trader_id, order_id, time_s, time_ns]
    
    Note: For type 4 (execute) orders, we flip the side as they represent 
    liquidity removal from the opposite side.
    """
    if n_msgs is not None:
        messages_df = messages_df.head(n_msgs)
    
    # Extract time components
    time_s = messages_df['time'].astype(int)
    time_ns = ((messages_df['time'] - time_s) * 1_000_000_000).astype(int)
    
    # Create JAX message array
    # Format: [type, side, quantity, price, trader_id, order_id, time_s, time_ns]
    msg_array = np.zeros((len(messages_df), 8), dtype=np.int32)
    msg_array[:, 0] = messages_df['type'].values  # type
    msg_array[:, 1] = messages_df['direction'].values  # side
    msg_array[:, 2] = messages_df['quantity'].values  # quantity
    msg_array[:, 3] = messages_df['price'].values  # price
    msg_array[:, 4] = messages_df['order_id'].values  # trader_id (use order_id)
    msg_array[:, 5] = messages_df['order_id'].values  # order_id
    msg_array[:, 6] = time_s.values  # time (seconds)
    msg_array[:, 7] = time_ns.values  # time_ns (nanoseconds)
    
    return jnp.array(msg_array)


def get_l2_from_orderbook_row(orderbook_row: np.ndarray, n_levels: int = 10) -> jnp.ndarray:
    """
    Convert a LOBSTER orderbook row to L2 format expected by init_msgs_from_l2.
    
    LOBSTER format: [ask_p1, ask_s1, bid_p1, bid_s1, ask_p2, ask_s2, bid_p2, bid_s2, ...]
    L2 format: [ask_p1, ask_s1, bid_p1, bid_s1, ask_p2, ask_s2, bid_p2, bid_s2, ...]
    
    The format is actually the same, so we just need to select the right columns.
    """
    return jnp.array(orderbook_row[:n_levels * 4].values, dtype=jnp.int32)


def create_message_dict(type_='limit', side='bid', price=2200000, quant=10, 
                        times=36000, timens=0, orderid=8888, traderid=8888):
    """Create a message dictionary compatible with the current API."""
    type_map = {'limit': 1, 'cancel': 2, 'delete': 3, 'market': 4}
    side_map = {'bid': 1, 'ask': -1}
    
    return {
        'side': side_map[side],
        'type': type_map[type_],
        'price': price,
        'quantity': quant,
        'orderid': orderid,
        'traderid': traderid,
        'time': times,
        'time_ns': timens
    }


def create_message_array(type_='limit', side='bid', price=2200000, quant=10,
                         times=36000, timens=0, orderid=8888, traderid=8888):
    """Create a message array compatible with cond_type_side."""
    type_map = {'limit': 1, 'cancel': 2, 'delete': 3, 'market': 4}
    side_map = {'bid': 1, 'ask': -1}
    
    return jnp.array([
        type_map[type_],
        side_map[side],
        quant,
        price,
        traderid,
        orderid,
        times,
        timens
    ], dtype=jnp.int32)

In [15]:
# ============================================================================
# Configuration and Data Loading
# ============================================================================

# Test configuration
n_runs = 1000
n_repeats = 5

# Create configuration with appropriate book depth
cfg = JAXLOB_Configuration(
    nOrders=100,   # Number of orders per side
    nTrades=100,   # Number of trades to track
    book_depth=10, # L2 book depth (matches LOBSTER data)
)

# Load sample data
messages_df, orderbook_df = load_sample_data()

# Get initial L2 state from first orderbook row
initial_l2 = get_l2_from_orderbook_row(orderbook_df.iloc[0], n_levels=cfg.book_depth)

print(f"\nConfiguration: nOrders={cfg.nOrders}, nTrades={cfg.nTrades}, book_depth={cfg.book_depth}")
print(f"Initial L2 state (first 8 values): {initial_l2[:8]}")
print(f"Best ask: {initial_l2[0]} @ {initial_l2[1]} shares")
print(f"Best bid: {initial_l2[2]} @ {initial_l2[3]} shares")

Loaded 269748 messages and 269748 orderbook states
Time range: 34200.02 to 57599.96
Message types: {1: 131954, 3: 123458, 4: 8974, 2: 2917, 5: 2445}

Configuration: nOrders=100, nTrades=100, book_depth=10
Initial L2 state (first 8 values): [2239500     100 2231800     100 2239900     100 2230700     200]
Best ask: 2239500 @ 100 shares
Best bid: 2231800 @ 100 shares


### Initialize Orderbook from Real L2 Data

Using `init_msgs_from_l2` to create messages that reconstruct the initial orderbook state from LOBSTER data.

In [16]:
# ============================================================================
# Initialize orderbook from L2 data using the OrderBook wrapper
# ============================================================================

# Create OrderBook instance
ob = OrderBook(cfg=cfg)

# Initialize with L2 data
initial_time = jnp.array([34200, 0])  # Market open time
state = ob.reset(l2_book=initial_l2, time=initial_time)

print("Initial orderbook state from LOBSTER L2 data:")
print(f"Asks shape: {state.asks.shape}")
print(f"Bids shape: {state.bids.shape}")
print(f"Trades shape: {state.trades.shape}")

# Get L2 state to verify
l2_state = job.get_L2_state(state.asks, state.bids, cfg.book_depth, cfg)
print(f"\nL2 state after initialization:")
print(f"Best Ask: {l2_state[0]} @ {l2_state[1]} shares")
print(f"Best Bid: {l2_state[2]} @ {l2_state[3]} shares")

# Show first few orders in each side
print(f"\nFirst 5 ask orders (price, qty, oid, tid, time_s, time_ns):")
valid_asks = state.asks[state.asks[:, 0] != -1]
print(valid_asks[:5])

print(f"\nFirst 5 bid orders (price, qty, oid, tid, time_s, time_ns):")
valid_bids = state.bids[state.bids[:, 0] != -1]
print(valid_bids[:5])

Initial orderbook state from LOBSTER L2 data:
Asks shape: (100, 6)
Bids shape: (100, 6)
Trades shape: (100, 8)

L2 state after initialization:
Best Ask: 2239500 @ 100 shares
Best Bid: 2231800 @ 100 shares

First 5 ask orders (price, qty, oid, tid, time_s, time_ns):
[[2239500     100      -2      -2   34200       0]
 [2239900     100      -4      -2   34200       0]
 [2240000     220      -6      -2   34200       0]
 [2242500     100      -8      -2   34200       0]
 [2244000     547     -10      -2   34200       0]]

First 5 bid orders (price, qty, oid, tid, time_s, time_ns):
[[2231800     100      -3      -2   34200       0]
 [2230700     200      -5      -2   34200       0]
 [2230400     100      -7      -2   34200       0]
 [2230000      10      -9      -2   34200       0]
 [2226200     100     -11      -2   34200       0]]


In [17]:
# ============================================================================
# Test Basic Operations: add_order
# ============================================================================

print("=" * 70)
print("Testing add_order on different book sizes")
print("=" * 70)

# Use the initialized state's bid side for testing
bids = state.bids.copy()

# Create a test message to add
mdict = create_message_dict(type_='limit', side='bid', price=2195000, quant=50)

# Warm up JIT
_ = job.add_order(bids, mdict)
jax.block_until_ready(_)

# Time the add_order operation
res = np.array(timeit.repeat(
    'val = job.add_order(bids, mdict); jax.block_until_ready(val)',
    repeat=n_repeats, number=n_runs, globals=globals()
))
mu = np.mean(res / n_runs)
sigma = np.std(res / n_runs)
mi = np.min(res / n_runs)
print(f"add_order time: mean={mu*1e6:.2f}µs, std={sigma*1e6:.2f}µs, min={mi*1e6:.2f}µs")

# Show the result
new_bids = job.add_order(bids, mdict)
print(f"\nAdded order: price={mdict['price']}, qty={mdict['quantity']}")
print(f"New order in book (last non-empty row):")
valid_new_bids = new_bids[new_bids[:, 0] != -1]
print(valid_new_bids[-1])

Testing add_order on different book sizes
add_order time: mean=75.95µs, std=0.86µs, min=74.31µs

Added order: price=2195000, qty=50
New order in book (last non-empty row):
[2195000      50    8888    8888   36000       0]


### Test cancel_order Operation

Cancel orders require the configuration object to handle different cancellation modes.

In [18]:
# ============================================================================
# Test cancel_order operation
# ============================================================================

print("=" * 70)
print("Testing cancel_order")
print("=" * 70)

# First add an order so we can cancel it
bids_with_order = job.add_order(bids, mdict)
key = jax.random.PRNGKey(cfg.seed)

# Create cancel message for the order we just added
cancel_dict = create_message_dict(
    type_='cancel', side='bid', 
    price=mdict['price'], quant=mdict['quantity'],
    orderid=mdict['orderid']
)

# Warm up JIT
_ = job.cancel_order(cfg, key, bids_with_order, cancel_dict)
jax.block_until_ready(_)

# Time the cancel_order operation
res = np.array(timeit.repeat(
    'val = job.cancel_order(cfg, key, bids_with_order, cancel_dict); jax.block_until_ready(val)',
    repeat=n_repeats, number=n_runs, globals=globals()
))
mu = np.mean(res / n_runs)
sigma = np.std(res / n_runs)
print(f"cancel_order time: mean={mu*1e6:.2f}µs, std={sigma*1e6:.2f}µs")

# Show the result
cancelled_bids = job.cancel_order(cfg, key, bids_with_order, cancel_dict)
print(f"\nBids before cancel: {jnp.sum(bids_with_order[:, 0] != -1)} orders")
print(f"Bids after cancel: {jnp.sum(cancelled_bids[:, 0] != -1)} orders")

Testing cancel_order
cancel_order time: mean=50.04µs, std=3.54µs

Bids before cancel: 11 orders
Bids after cancel: 10 orders


### Test Matching Functions

Match incoming orders against the best orders on the opposite side of the book.

In [19]:
# ============================================================================
# Test matching functions
# ============================================================================

print("=" * 70)
print("Testing _get_top_bid_order_idx and _get_top_ask_order_idx")
print("=" * 70)

# Get top bid order index
top_bid_idx = job._get_top_bid_order_idx(cfg, state.bids)
top_ask_idx = job._get_top_ask_order_idx(cfg, state.asks)

print(f"Top bid order index: {top_bid_idx}")
print(f"Top bid order: {state.bids[top_bid_idx].squeeze()}")
print(f"Top ask order index: {top_ask_idx}")
print(f"Top ask order: {state.asks[top_ask_idx].squeeze()}")

# Time the get_top operations
res_bid = np.array(timeit.repeat(
    'val = job._get_top_bid_order_idx(cfg, state.bids); jax.block_until_ready(val)',
    repeat=n_repeats, number=n_runs, globals=globals()
))
res_ask = np.array(timeit.repeat(
    'val = job._get_top_ask_order_idx(cfg, state.asks); jax.block_until_ready(val)',
    repeat=n_repeats, number=n_runs, globals=globals()
))
print(f"\n_get_top_bid_order_idx time: mean={np.mean(res_bid/n_runs)*1e6:.2f}µs")
print(f"_get_top_ask_order_idx time: mean={np.mean(res_ask/n_runs)*1e6:.2f}µs")

# ============================================================================
# Test _match_against_bid_orders
# ============================================================================

print("\n" + "=" * 70)
print("Testing _match_against_bid_orders")
print("=" * 70)

# Create an incoming sell (ask) order that should match against bids
trades = (jnp.ones((cfg.nTrades, 8), dtype=jnp.int32) * -1)
incoming_qty = 50
incoming_price = 0  # Will match any bid (aggressive market sell)

# Match against bids
matched_bids, remaining_qty, _, matched_trades = job._match_against_bid_orders(
    cfg, state.bids, incoming_qty, incoming_price, trades,
    agrOID=9999, time=36000, time_ns=0, agrTID=9999, side=-1
)

print(f"Incoming sell order: qty={incoming_qty}, price={incoming_price} (market order)")
print(f"Remaining qty after matching: {remaining_qty}")
print(f"Number of trades recorded: {jnp.sum(matched_trades[:, 0] != -1)}")
print(f"First trade: {matched_trades[0]}")

# Time the matching operation
timing_code = """
val = job._match_against_bid_orders(
    cfg, state.bids, incoming_qty, incoming_price, trades,
    agrOID=9999, time=36000, time_ns=0, agrTID=9999, side=-1)
jax.block_until_ready(val)
"""
res = np.array(timeit.repeat(timing_code, repeat=n_repeats, number=n_runs, globals=globals()))
print(f"\n_match_against_bid_orders time: mean={np.mean(res/n_runs)*1e6:.2f}µs")

Testing _get_top_bid_order_idx and _get_top_ask_order_idx
Top bid order index: [0]
Top bid order: [2231800     100      -3      -2   34200       0]
Top ask order index: [0]
Top ask order: [2239500     100      -2      -2   34200       0]

_get_top_bid_order_idx time: mean=34.62µs
_get_top_ask_order_idx time: mean=33.08µs

Testing _match_against_bid_orders
Incoming sell order: qty=50, price=0 (market order)
Remaining qty after matching: -50
Number of trades recorded: 1
First trade: [2231800      50      -3    9999   36000       0      -2    9999]

_match_against_bid_orders time: mean=152.73µs


### Test cond_type_side - Full Message Processing

The `cond_type_side` function is the main branching function that routes messages to the appropriate handler based on type and side.

In [20]:
# ============================================================================
# Test cond_type_side - Full message processing pipeline
# ============================================================================

print("=" * 70)
print("Testing cond_type_side with different message types")
print("=" * 70)

# Reset to initial state
state = ob.reset(l2_book=initial_l2, time=initial_time)
asks, bids, trades = state.asks, state.bids, state.trades
key = jax.random.PRNGKey(cfg.seed)

# Test 1: Limit order (bid)
limit_msg = create_message_array(type_='limit', side='bid', price=2195000, quant=77)
book_state = (asks, bids, trades)
key, split_key = jax.random.split(key)
new_state, _ = job.cond_type_side(cfg, book_state, (split_key, limit_msg))
print(f"After limit bid order:")
print(f"  Bids count: {jnp.sum(bids[:, 0] != -1)} -> {jnp.sum(new_state[1][:, 0] != -1)}")

# Time limit order
res = np.array(timeit.repeat(
    'val = job.cond_type_side(cfg, book_state, (split_key, limit_msg)); jax.block_until_ready(val)',
    repeat=n_repeats, number=n_runs, globals=globals()
))
print(f"  Time: mean={np.mean(res/n_runs)*1e6:.2f}µs")

# Test 2: Cancel order (bid)
cancel_msg = create_message_array(type_='cancel', side='bid', price=2195000, quant=77, orderid=8888)
key, split_key = jax.random.split(key)
cancelled_state, _ = job.cond_type_side(cfg, new_state, (split_key, cancel_msg))
print(f"\nAfter cancel bid order:")
print(f"  Bids count: {jnp.sum(new_state[1][:, 0] != -1)} -> {jnp.sum(cancelled_state[1][:, 0] != -1)}")

# Time cancel order
book_state = new_state
res = np.array(timeit.repeat(
    'val = job.cond_type_side(cfg, book_state, (split_key, cancel_msg)); jax.block_until_ready(val)',
    repeat=n_repeats, number=n_runs, globals=globals()
))
print(f"  Time: mean={np.mean(res/n_runs)*1e6:.2f}µs")

# Test 3: Crossing limit order (should match)
# Get best bid price and submit a sell order at that price
best_bid_price = jnp.max(state.bids[:, 0])
cross_msg = create_message_array(type_='limit', side='ask', price=int(best_bid_price), quant=25)
key, split_key = jax.random.split(key)
book_state = (state.asks, state.bids, state.trades)
crossed_state, _ = job.cond_type_side(cfg, book_state, (split_key, cross_msg))
print(f"\nAfter crossing limit order (sell at best bid {best_bid_price}):")
print(f"  Trades recorded: {jnp.sum(crossed_state[2][:, 0] != -1)}")
print(f"  First trade: {crossed_state[2][0]}")

# Time crossing order
res = np.array(timeit.repeat(
    'val = job.cond_type_side(cfg, book_state, (split_key, cross_msg)); jax.block_until_ready(val)',
    repeat=n_repeats, number=n_runs, globals=globals()
))
print(f"  Time: mean={np.mean(res/n_runs)*1e6:.2f}µs")

Testing cond_type_side with different message types
After limit bid order:
  Bids count: 10 -> 11
  Time: mean=299.96µs

After cancel bid order:
  Bids count: 11 -> 10
  Time: mean=267.82µs

After crossing limit order (sell at best bid 2231800):
  Trades recorded: 1
  First trade: [2231800      25      -3    8888   36000       0      -2    8888]
  Time: mean=239.52µs


### Process Real LOBSTER Messages

Use `scan_through_entire_array` to process a batch of real LOBSTER messages through the orderbook.

In [21]:
# ============================================================================
# Process real LOBSTER messages using scan_through_entire_array
# ============================================================================

print("=" * 70)
print("Processing real LOBSTER messages with scan_through_entire_array")
print("=" * 70)

# Filter messages to only include types we handle (1=limit, 2=cancel, 3=delete, 4=execute)
valid_types = [1, 2, 3, 4]
filtered_messages = messages_df[messages_df['type'].isin(valid_types)].copy()
print(f"Filtered {len(messages_df)} -> {len(filtered_messages)} messages (types: {valid_types})")

# Convert to JAX format
n_msgs_to_process = 200  # Process first 200 messages (reduced for stability)
jax_messages = preprocess_messages_to_jax(filtered_messages, n_msgs=n_msgs_to_process)
print(f"Processing {len(jax_messages)} messages")

# Reset orderbook to initial state
state = ob.reset(l2_book=initial_l2, time=initial_time)
initial_asks, initial_bids, initial_trades = state.asks, state.bids, state.trades
key = jax.random.PRNGKey(cfg.seed)

# Get L2 state before processing
l2_before = job.get_L2_state(initial_asks, initial_bids, cfg.book_depth, cfg)
print(f"\nL2 state BEFORE processing:")
print(f"  Best Ask: {l2_before[0]} @ {l2_before[1]}")
print(f"  Best Bid: {l2_before[2]} @ {l2_before[3]}")

# Process all messages
book_state = (initial_asks, initial_bids, initial_trades)
final_state = job.scan_through_entire_array(cfg, key, jax_messages, book_state)
final_asks, final_bids, final_trades = final_state

# Get L2 state after processing
l2_after = job.get_L2_state(final_asks, final_bids, cfg.book_depth, cfg)
print(f"\nL2 state AFTER processing {n_msgs_to_process} messages:")
print(f"  Best Ask: {l2_after[0]} @ {l2_after[1]}")
print(f"  Best Bid: {l2_after[2]} @ {l2_after[3]}")
print(f"  Total trades recorded: {jnp.sum(final_trades[:, 0] != -1)}")

# Timing (reduced iterations)
import time as time_module
times = []
for _ in range(5):
    start = time_module.perf_counter()
    val = job.scan_through_entire_array(cfg, key, jax_messages, book_state)
    jax.block_until_ready(val)
    times.append(time_module.perf_counter() - start)

mean_time = np.mean(times)
print(f"\nscan_through_entire_array ({n_msgs_to_process} messages):")
print(f"  Total time: mean={mean_time*1000:.2f}ms")
print(f"  Per message: mean={mean_time/n_msgs_to_process*1e6:.2f}µs")

Processing real LOBSTER messages with scan_through_entire_array
Filtered 269748 -> 267303 messages (types: [1, 2, 3, 4])
Processing 200 messages

L2 state BEFORE processing:
  Best Ask: 2239500 @ 100
  Best Bid: 2231800 @ 100

L2 state AFTER processing 200 messages:
  Best Ask: 2240200 @ 200
  Best Bid: 2238900 @ 200
  Total trades recorded: 65

scan_through_entire_array (200 messages):
  Total time: mean=487.81ms
  Per message: mean=2439.03µs


### Test VMAP for Parallel Processing

Test vectorized operations for processing multiple orderbooks in parallel.

In [22]:
# ============================================================================
# Test VMAP - Vectorized parallel processing
# ============================================================================

print("=" * 70)
print("Testing VMAP for parallel orderbook processing")
print("=" * 70)

nvmap = 32  # Number of parallel orderbooks (reduced for CPU stability)

# Create batched states
state = ob.reset(l2_book=initial_l2, time=initial_time)
vasks = jnp.array([state.asks] * nvmap)
vbids = jnp.array([state.bids] * nvmap)
vtrades = jnp.array([state.trades] * nvmap)

# Create batched messages (same message for all)
limit_msg = create_message_array(type_='limit', side='bid', price=2195000, quant=77)
vlimit_msgs = jnp.array([limit_msg] * nvmap)

# Batched keys
key = jax.random.PRNGKey(cfg.seed)
vkeys = jax.random.split(key, nvmap)

# VMAP cond_type_side
print(f"VMAP cond_type_side over {nvmap} orderbooks:")
vmapped_cond = jax.vmap(
    lambda books, key_msg: job.cond_type_side(cfg, books, key_msg),
    in_axes=((0, 0, 0), (0, 0))
)

# Warm up
book_states = (vasks, vbids, vtrades)
it_data = (vkeys, vlimit_msgs)
_ = vmapped_cond(book_states, it_data)
jax.block_until_ready(_)

# Time VMAP with simple timing
import time as time_module
times_vmap = []
for _ in range(10):
    start = time_module.perf_counter()
    val = vmapped_cond(book_states, it_data)
    jax.block_until_ready(val)
    times_vmap.append(time_module.perf_counter() - start)

mean_vmap = np.mean(times_vmap)
print(f"  Total time for {nvmap} orderbooks: mean={mean_vmap*1000:.2f}ms")
print(f"  Per orderbook: mean={mean_vmap/nvmap*1e6:.2f}µs")

# Time single orderbook for comparison
times_single = []
single_state = (state.asks, state.bids, state.trades)
single_key, _ = jax.random.split(key)
for _ in range(10):
    start = time_module.perf_counter()
    val = job.cond_type_side(cfg, single_state, (single_key, limit_msg))
    jax.block_until_ready(val)
    times_single.append(time_module.perf_counter() - start)

mean_single = np.mean(times_single)
print(f"\nSingle orderbook processing:")
print(f"  Time: mean={mean_single*1e6:.2f}µs")
print(f"  Theoretical {nvmap}x sequential: {mean_single * nvmap * 1000:.2f}ms")
print(f"  VMAP efficiency: {(mean_single * nvmap) / mean_vmap:.1f}x speedup")

Testing VMAP for parallel orderbook processing
VMAP cond_type_side over 32 orderbooks:
  Total time for 32 orderbooks: mean=1.78ms
  Per orderbook: mean=55.69µs

Single orderbook processing:
  Time: mean=399.85µs
  Theoretical 32x sequential: 12.80ms
  VMAP efficiency: 7.2x speedup


### Summary of Performance Results

In [23]:
# ============================================================================
# Summary and Visualization of L2 Book States
# ============================================================================

print("=" * 70)
print("Final Summary - L2 Book State Comparison")
print("=" * 70)

# Get fresh states
state = ob.reset(l2_book=initial_l2, time=initial_time)
key = jax.random.PRNGKey(cfg.seed)

# Process messages with state saving (reduced for stability)
n_msgs_to_save = 50
jax_messages_subset = jax_messages[:n_msgs_to_save]
book_state = (state.asks, state.bids, state.trades)

# Use scan_through_entire_array_save_bidask to track bid/ask evolution
final_state, bid_ask_history = job.scan_through_entire_array_save_bidask(
    cfg, key, jax_messages_subset, book_state, n_msgs_to_save
)

# bid_ask_history[0] = best ask info, bid_ask_history[1] = best bid info
# (Note: function returns (ask, bid) in that order)
best_asks = bid_ask_history[0]
best_bids = bid_ask_history[1]

print(f"Processed {n_msgs_to_save} messages with bid/ask tracking")
print(f"\nAsk prices (first 10): {best_asks[:10, 0]}")
print(f"Bid prices (first 10): {best_bids[:10, 0]}")

# Calculate spread evolution
spreads = best_asks[:, 0] - best_bids[:, 0]
print(f"\nSpread statistics:")
print(f"  Mean spread: {jnp.mean(spreads):.0f}")
print(f"  Min spread: {jnp.min(spreads):.0f}")
print(f"  Max spread: {jnp.max(spreads):.0f}")

# Final L2 state
l2_final = job.get_L2_state(final_state[0], final_state[1], cfg.book_depth, cfg)
print(f"\nFinal L2 state (top 3 levels):")
print(f"  Ask L1: {l2_final[0]} @ {l2_final[1]}")
print(f"  Ask L2: {l2_final[4]} @ {l2_final[5]}")  
print(f"  Ask L3: {l2_final[8]} @ {l2_final[9]}")
print(f"  Bid L1: {l2_final[2]} @ {l2_final[3]}")
print(f"  Bid L2: {l2_final[6]} @ {l2_final[7]}")
print(f"  Bid L3: {l2_final[10]} @ {l2_final[11]}")

print("\n" + "=" * 70)
print("All tests completed successfully!")
print("=" * 70)

Final Summary - L2 Book State Comparison
Processed 50 messages with bid/ask tracking

Ask prices (first 10): [2239500 2239500 2239500 2239500 2239500 2239500 2239500 2239500 2239500
 2239500]
Bid prices (first 10): [2238100 2238100 2238100 2238100 2238100 2238100 2238100 2238100 2238100
 2238100]

Spread statistics:
  Mean spread: 1730
  Min spread: 1400
  Max spread: 2500

Final L2 state (top 3 levels):
  Ask L1: 2240000 @ 1338
  Ask L2: 2242400 @ 20
  Ask L3: 2242500 @ 100
  Bid L1: 2237500 @ 74
  Bid L2: 2236500 @ 2
  Bid L3: 2236200 @ 286

All tests completed successfully!
