In [2]:
import sys
import importlib
sys.path.append('/Users/sasrey/AlphaTrade/gym_exchange')
sys.path.insert(0, "/Users/sasrey/NeuralLOB/gym_exchange/")
sys.path.append('/Users/sasrey/AlphaTrade')

import timeit


In [35]:
import jaxob.JaxOrderbook as job
import jax.numpy as jnp
from jax import lax
import jax


In [4]:
from orderbook import OrderBook
import gym_exchange.data_orderbook_adapter.data_pipeline as dpl
from gym_exchange.data_orderbook_adapter.decoder import Decoder
from gym_exchange.data_orderbook_adapter.encoder import Encoder

order_book_cpu = OrderBook()

In [36]:
dpl=importlib.reload(dpl)

In [37]:
dplOBJ=dpl.DataPipeline()
decodeddata=Decoder(10,40,dplOBJ.historical_data,dplOBJ.data_loader)
decodeddata.initialize_orderbook()
output=decodeddata.process()
enc=Encoder(decodeddata)
enc()

AssertionError: 

In [ ]:
enc()

In [5]:
item = {'type' : 'limit', 
        'side' : 'bid', 
        'quantity' : 100, 
        'price' : 24567,
        'trade_id' : 11111,
        'order_id' : 0,
        "timestamp": str(34200.000000001)}

In [7]:
%timeit order_book.process_order(item,True,False)

3.21 µs ± 14.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [6]:
import pandas as pd
df_msg = pd.read_csv("/Users/sasrey/project-RL4ABM/data_tqap/TSLA_2015-01-01_2015-01-31_10/TSLA_2015-01-02_34200000_57600000_message_10.csv", header=None)
df_ob = pd.read_csv("/Users/sasrey/project-RL4ABM/data_tqap/TSLA_2015-01-01_2015-01-31_10/TSLA_2015-01-02_34200000_57600000_orderbook_10.csv", header=None)

In [7]:
data=jnp.array(df_ob.iloc[0,:]).reshape(20,2)
newarr=jnp.zeros((20,7))
initOB=newarr.at[:,3].set(data[:,0]).at[:,2].set(data[:,1]).at[:,0].set(1).at[0:40:2,1].set(-1).at[1:40:2,1].set(1).at[:,4].set(0).at[:,5].set(job.INITID).at[:,6].set(34200.00000000)
initOB[0]

Array([ 1.00000e+00, -1.00000e+00,  1.50700e+03,  2.22910e+06,
        0.00000e+00, -9.99999e+05,  3.42000e+04], dtype=float32)

In [8]:
df_orders=df_msg.rename(columns={1:'Type',5:'Side',3:'Quantity',4:'Price',2:'OrderID',0:'Time'})
df_orders['TradeID']=0
col_order=['Type','Side','Quantity','Price','TradeID','OrderID','Time']
df_orders=df_orders[col_order]
df_orders_simple=df_orders[(df_orders['Type']!=6)&(df_orders['Type']!=7)&(df_orders['Type']!=5)]
df_orders

Type  Side  Quantity    Price  TradeID    OrderID          Time
0          5     1        13  2228300        0          0  34200.006789
1          6    -1     17011  2228700        0         -1  34200.034290
2          1     1        11  2227500        0    5519048  34200.034290
3          1    -1        10  2230000        0    2142274  34200.034290
4          1     1       200  2226000        0    2629509  34200.034290
...      ...   ...       ...      ...      ...        ...           ...
216706     4    -1        39  2193100        0  267961846  57599.977910
216707     4    -1        61  2193100        0  267963915  57599.977910
216708     1     1       100  2191900        0  267983787  57599.977975
216709     3    -1       100  2193100        0  267981940  57599.978001
216710     1    -1       100  2193200        0  267983788  57599.978001

[216711 rows x 7 columns]

In [9]:
df_ob

0     1        2     3        4    5        6     7        8   \
0       2229100  1507  2226400   300  2234000   50  2222200   200  2237200   
1       2229100  1507  2226400   300  2234000   50  2222200   200  2237200   
2       2229100  1507  2227500    11  2234000   50  2226400   300  2237200   
3       2229100  1507  2227500    11  2230000   10  2226400   300  2234000   
4       2229100  1507  2227500    11  2230000   10  2226400   300  2234000   
...         ...   ...      ...   ...      ...  ...      ...   ...      ...   
216706  2193100   600  2191900  1000  2193400  200  2191700  2600  2194100   
216707  2193100   539  2191900  1000  2193400  200  2191700  2600  2194100   
216708  2193100   539  2191900  1100  2193400  200  2191700  2600  2194100   
216709  2193100   439  2191900  1100  2193400  200  2191700  2600  2194100   
216710  2193100   439  2191900  1100  2193200  100  2191700  2600  2193400   

         9   ...       30    31       32    33       34   35       36    37  \
0       300  ...  2203200   100  2252500    20  2200000   97  2257500    40   
1       300  ...  2203200   100  2252500    20  2200000   97  2257500    40   
2       300  ...  2210000   100  2252500    20  2203200  100  2257500    40   
3        50  ...  2210000   100  2250000   100  2203200  100  2252500    20   
4        50  ...  2218300    20  2250000   100  2210000  100  2252500    20   
...     ...  ...      ...   ...      ...   ...      ...  ...      ...   ...   
216706  100  ...  2190700  1619  2195800   600  2190600  100  2196000  2200   
216707  100  ...  2190700  1619  2195800   600  2190600  100  2196000  2200   
216708  100  ...  2190700  1619  2195800   600  2190600  100  2196000  2200   
216709  100  ...  2190700  1619  2195800   600  2190600  100  2196000  2200   
216710  200  ...  2190700  1619  2195700  3000  2190600  100  2195800   600   

             38   39  
0       2190000   50  
1       2190000   50  
2       2200000   97  
3       2200000   97  
4       2203200  100  
...         ...  ...  
216706  2190500  200  
216707  2190500  200  
216708  2190500  200  
216709  2190500  200  
216710  2190500  200  

[216711 rows x 40 columns]

In [10]:
ordersJNP=jnp.array(df_orders)
ordersJNP.shape

(216711, 7)

In [28]:
##### For testing purposes: Assume that the first entry in the LOB is a series of single orders.
def initorderbook(orderbookstate):
    orderbookDimension=[2,10,5,5]
    orderbook=jnp.ones(orderbookDimension)*-1
    orderbook,test=lax.scan(job.processOrder,orderbook,orderbookstate)
    return orderbook

@jax.jit
def applyMessages(orderbook,msg):
    orderbook,trades=lax.scan(job.processOrder,orderbook,msg)
    return (orderbook,trades)

In [29]:
orderbook=initorderbook(initOB)
#%timeit job.processOrder(orderbook,jnp.array([1.,1.,100.,145564.,0.,111111.,3400000.]))

In [30]:
job=importlib.reload(jaxob.JaxOrderbook)

NameError: name 'jaxob' is not defined

In [34]:
%timeit applyMessages(orderbook,ordersJNP[0:100000])#.block_until_ready()

133 ms ± 151 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [598]:
orderbook=initorderbook(initOB)
start = timeit.timeit()
orderbook,trades=applyMessages(orderbook,ordersJNP[0:35])
end = timeit.timeit()
print(end - start)


-0.0023344989167526364


In [599]:
trades

Array([[[-1.0000000e+00, -1.0000000e+00, -1.0000000e+00, -1.0000000e+00,
         -1.0000000e+00, -1.0000000e+00],
        [-1.0000000e+00, -1.0000000e+00, -1.0000000e+00, -1.0000000e+00,
         -1.0000000e+00, -1.0000000e+00],
        [-1.0000000e+00, -1.0000000e+00, -1.0000000e+00, -1.0000000e+00,
         -1.0000000e+00, -1.0000000e+00],
        [-1.0000000e+00, -1.0000000e+00, -1.0000000e+00, -1.0000000e+00,
         -1.0000000e+00, -1.0000000e+00],
        [-1.0000000e+00, -1.0000000e+00, -1.0000000e+00, -1.0000000e+00,
         -1.0000000e+00, -1.0000000e+00]],

       [[-1.0000000e+00, -1.0000000e+00, -1.0000000e+00, -1.0000000e+00,
         -1.0000000e+00, -1.0000000e+00],
        [-1.0000000e+00, -1.0000000e+00, -1.0000000e+00, -1.0000000e+00,
         -1.0000000e+00, -1.0000000e+00],
        [-1.0000000e+00, -1.0000000e+00, -1.0000000e+00, -1.0000000e+00,
         -1.0000000e+00, -1.0000000e+00],
        [-1.0000000e+00, -1.0000000e+00, -1.0000000e+00, -1.0000000e+00,
     

In [526]:
orderbook[:,0:15,0,:] #Currently missing some orders on bid-side (Prices: 22222,22221,22220): this is precisly the issue of the limited levels 

Array([[[ 1.5070000e+03,  2.2291000e+06,  0.0000000e+00, -9.9999900e+05,
          3.4200000e+04],
        [ 1.0000000e+01,  2.2300000e+06,  0.0000000e+00,  2.1422740e+06,
          3.4200035e+04],
        [ 2.3000000e+01,  2.2335000e+06,  0.0000000e+00,  1.3107120e+06,
          3.4200035e+04],
        [ 5.0000000e+01,  2.2340000e+06,  0.0000000e+00, -9.9999900e+05,
          3.4200000e+04],
        [ 3.9000000e+02,  2.2350000e+06,  0.0000000e+00,  7.4562070e+06,
          3.4200262e+04],
        [ 3.0000000e+02,  2.2372000e+06,  0.0000000e+00, -9.9999900e+05,
          3.4200000e+04],
        [ 1.0000000e+02,  2.2375000e+06,  0.0000000e+00, -9.9999900e+05,
          3.4200000e+04],
        [ 2.0000000e+02,  2.2400000e+06,  0.0000000e+00, -9.9999900e+05,
          3.4200000e+04],
        [ 1.0000000e+02,  2.2410000e+06,  0.0000000e+00,  4.8959150e+06,
          3.4200035e+04],
        [ 2.0000000e+01,  2.2425000e+06,  0.0000000e+00, -9.9999900e+05,
          3.4200000e+04],
        [ 

In [582]:
trades

Array([[[-1.0000000e+00, -1.0000000e+00, -1.0000000e+00, -1.0000000e+00,
         -1.0000000e+00, -1.0000000e+00],
        [-1.0000000e+00, -1.0000000e+00, -1.0000000e+00, -1.0000000e+00,
         -1.0000000e+00, -1.0000000e+00]],

       [[-1.0000000e+00, -1.0000000e+00, -1.0000000e+00, -1.0000000e+00,
         -1.0000000e+00, -1.0000000e+00],
        [-1.0000000e+00, -1.0000000e+00, -1.0000000e+00, -1.0000000e+00,
         -1.0000000e+00, -1.0000000e+00]],

       [[-1.0000000e+00, -1.0000000e+00, -1.0000000e+00,  5.5190480e+06,
         -1.0000000e+00,  3.4200035e+04],
        [-1.0000000e+00, -1.0000000e+00, -1.0000000e+00,  5.5190480e+06,
         -1.0000000e+00,  3.4200035e+04]],

       [[-1.0000000e+00, -1.0000000e+00, -1.0000000e+00,  2.1422740e+06,
         -1.0000000e+00,  3.4200035e+04],
        [-1.0000000e+00, -1.0000000e+00, -1.0000000e+00,  2.1422740e+06,
         -1.0000000e+00,  3.4200035e+04]],

       [[-1.0000000e+00, -1.0000000e+00, -1.0000000e+00,  2.6295090e+06,